# Generated by Django 2.2.3 on 2019-07-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190712_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
